"""
SSH to the HPC login node (vrhpcadm1) over Tailscale.

Connectivity comes from the tailscale operator's egress proxy — the
ExternalName Service in k8s/api.yaml resolves "vrhpcadm1" to a proxy pod that
forwards TCP out to the tailnet. Nothing tailscale-specific happens here; from
this module's point of view it is an ordinary hostname on port 22.

Auth is Tailscale SSH: the proxy device is tagged tag:k8s, tailscaled on
vrhpcadm1 intercepts port 22 and authorizes by ACL, so no key material is
needed. Set HPC_SSH_KEY to a private key path to fall back to normal sshd key
auth instead.
"""

import os
import asyncio

import asyncssh

SSH_HOST = os.getenv("HPC_SSH_HOST", "vrhpcadm1")
SSH_USER = os.getenv("HPC_SSH_USER", "")
SSH_KEY = os.getenv("HPC_SSH_KEY")  # unset ⇒ keyless, via the Tailscale SSH ACL


class RemoteError(RuntimeError):
    """Anything that stopped the command from running to completion.

    Routes map this to a 502 — the failure is on the far side of the tailnet,
    not in the request. asyncssh types never escape this module.
    """


async def run(cmd: str, timeout: float = 30) -> tuple[int, str, str]:
    """Run `cmd` on the login node, returning (exit_status, stdout, stderr).

    A non-zero exit status is returned, not raised: callers like `squeue` care
    about the difference between "the command said no" and "we never got
    there". Only the latter raises.
    """
    if not SSH_USER:
        raise RemoteError("HPC_SSH_USER is unset — see k8s/api.yaml")

    try:
        async with asyncssh.connect(
            SSH_HOST,
            username=SSH_USER,
            # The host key is generated by tailscaled on the far side and there
            # is no stable entry to pin; the tailnet is the trust boundary.
            known_hosts=None,
            client_keys=[SSH_KEY] if SSH_KEY else None,
            connect_timeout=timeout,
        ) as conn:
            result = await asyncio.wait_for(
                conn.run(cmd, check=False), timeout=timeout
            )
    except asyncio.TimeoutError:
        raise RemoteError(f"{SSH_HOST}: timed out after {timeout}s running: {cmd}")
    except (OSError, asyncssh.Error) as exc:
        raise RemoteError(f"{SSH_HOST}: {exc}") from exc

    return (
        result.exit_status,
        (result.stdout or "").strip(),
        (result.stderr or "").strip(),
    )


async def check(cmd: str, timeout: float = 30) -> str:
    """`run`, but a non-zero exit status is an error too. Returns stdout."""
    status, out, err = await run(cmd, timeout=timeout)
    if status != 0:
        raise RemoteError(f"{cmd!r} exited {status}: {err or out}")
    return out
